---
manage_pip_packages_install_prereqs: true
manage_pip_packages_list:
  - name: docker
    version_constraint: latest
    state: present
  - name: yamllint
    version_constraint: '==1.24'
    state: present
  - name: vault-cli
    version_constraint: '<3.1.0'
    state: present
